services:
  db:
    image: postgres:15
    container_name: fastapi_pg_db
    restart: always
    environment:
      POSTGRES_DB: filesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
      - files:/code/uploaded_files
    ports:
      - "8000:8000"
    depends_on:
      - db
      - neo4j
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/filesdb
      SECRET_KEY: your-secret-key
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: your_neo4j_password

  neo4j:
    image: neo4j:5
    container_name: keypg_neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/your_neo4j_password
      NEO4J_dbms_memory_pagecache_size: 256M
      NEO4J_dbms_memory_heap_initial__size: 512M
      NEO4J_dbms_memory_heap_max__size: 1G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data

volumes:
  pgdata:
  files:
  neo4j-data: