services:
  db:
    image: postgres:15
    container_name: fastapi_pg_db
    restart: always
    environment:
      POSTGRES_DB: filesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
      - files:/code/uploaded_files
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/filesdb
      SECRET_KEY: your-secret-key

volumes:
  pgdata:
  files:
